version: '3.8'

services:
  mikrotik-api:
    build: .
    container_name: mikrotik_rest_api
    env_file:
      - .env
    networks:
      - kuma-net
    restart: unless-stopped

networks:
  kuma-net:
    external: true